/*
 * Copyright 2018 ebouzekr.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package m2.ihm.ui;

import m2.ihm.core.home.Home;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import m2.ihm.core.home.IHomeStorageProvider;

/**
 *
 * @author ebouzekr
 */
public class NupletsUI extends javax.swing.JFrame {

    private enum State {
        //To complete
    }

    // Error message for incorrect entry
    private static final String ERROR_MESSAGE = "Un des champs est vide ou incorrect";
    // Manage homes in BDD
    private IHomeStorageProvider homeStorageProvider;
    // Application state
    private State state;
    // State variable
    private int n;
    // Temporary storage of home
    private Home temp;
    // Selected home name in list
    private String selectedValue;

    /**
     * Creates new form NupletsUI
     */
    public NupletsUI(IHomeStorageProvider provider) {
        initComponents();
        bddList.setModel(new DefaultListModel<>());
        init(provider);
    }

    private void init(IHomeStorageProvider provider) {
        homeStorageProvider = provider;
        updateTable(homeStorageProvider.getHomes());
        //To complete
    }

    private void goToState(State state) {
        //To complete
    }

    private void setPrice() {
        prixValueLabel.setText(String.valueOf(prixSlider.getValue()));
    }

    private boolean correct() {
        return (!(nombienTextField.getText().isEmpty()
                || latFormattedTextField.getText().isEmpty()
                || longFormattedTextField.getText().isEmpty()
                || superficieFormattedTextField.getText().isEmpty()
                || ((int) nbpiecesSpinner.getValue()) < 0
                || prixSlider.getValue() < 0));
    }

    private void selectionner() {
        selectedValue = getSelection();
        temp = homeStorageProvider.getHomeByName(selectedValue);
        nombienTextField.setText(temp.getName());
        typebienButtonGroup.clearSelection();
        appartementRadioButton.setSelected(temp.getType().equals("Appartement"));
        maisonRadioButton.setSelected(temp.getType().equals("Maison"));
        //To complete
    }

    private void remplacer() {
        //To complete
    }

    private void ajouter() {
        //To complete
    }

    private void supprimer() {
        //To complete
    }

    private void retablir() {
        //To complete
    }

    private int getNbRow() {
        return ((DefaultListModel) bddList.getModel()).getSize();
    }

    private String getSelection() {
        return bddList.getSelectedValue();
    }

    private void updateTable(List<Home> homes) {
        ((DefaultListModel) bddList.getModel()).removeAllElements();
        for (Home h : homes) {
            ((DefaultListModel) bddList.getModel()).addElement(h.getName());
        }
        bddList.revalidate();
        bddjScrollPane.revalidate();
        selectedValue = getSelection();
        if (selectedValue != null && !selectedValue.isEmpty()) {
            bddList.setSelectedValue(selectedValue, true);
        } else {
            bddList.setSelectedIndex(0);
        }
    }

    private void popupmessage() {
        JOptionPane.showMessageDialog(this, ERROR_MESSAGE, "Inane error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typebienButtonGroup = new javax.swing.ButtonGroup();
        attributesPanel = new javax.swing.JPanel();
        attributesNamePanel = new javax.swing.JPanel();
        typePanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        appartementRadioButton = new javax.swing.JRadioButton();
        maisonRadioButton = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        nombienPanel = new javax.swing.JPanel();
        nombienLabel = new javax.swing.JLabel();
        nombienTextField = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        localisationPanel = new javax.swing.JPanel();
        localisationLabel = new javax.swing.JLabel();
        latFormattedTextField = new javax.swing.JFormattedTextField();
        latLabel = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 0));
        longFormattedTextField = new javax.swing.JFormattedTextField();
        longLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        superficiePanel = new javax.swing.JPanel();
        superficieLabel = new javax.swing.JLabel();
        superficieFormattedTextField = new javax.swing.JFormattedTextField();
        metrecarreLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        nbpiecesPanel = new javax.swing.JPanel();
        nbpiecesLabel = new javax.swing.JLabel();
        nbpiecesSpinner = new javax.swing.JSpinner();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        commoditesPanel = new javax.swing.JPanel();
        commoditesLabel = new javax.swing.JLabel();
        parkingCheckBox = new javax.swing.JCheckBox();
        piscineCheckBox = new javax.swing.JCheckBox();
        terrasseCheckBox = new javax.swing.JCheckBox();
        jardinCheckBox = new javax.swing.JCheckBox();
        caveCheckBox = new javax.swing.JCheckBox();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 32767));
        prixPanel = new javax.swing.JPanel();
        prixLabel = new javax.swing.JLabel();
        prixSlider = new javax.swing.JSlider();
        prixValueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 15));
        jPanel2 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ajouterButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        retablirButton = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15));
        jPanel1 = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        supprimerButton = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        remplacerButton = new javax.swing.JButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        bddjScrollPane = new javax.swing.JScrollPane();
        bddList = new javax.swing.JList<>();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuplets");
        setMinimumSize(new java.awt.Dimension(470, 470));
        setPreferredSize(new java.awt.Dimension(470, 470));

        attributesPanel.setPreferredSize(new java.awt.Dimension(457, 280));
        attributesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesPanel.setLayout(new java.awt.BorderLayout());

        attributesNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saisie d'un Bien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        attributesNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.setLayout(new javax.swing.BoxLayout(attributesNamePanel, javax.swing.BoxLayout.Y_AXIS));

        typePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        typePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        typeLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        typeLabel.setText("Type de bien : ");
        typeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        typePanel.add(typeLabel);

        typebienButtonGroup.add(appartementRadioButton);
        appartementRadioButton.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        appartementRadioButton.setSelected(true);
        appartementRadioButton.setText("Appartement");
        appartementRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        typePanel.add(appartementRadioButton);

        typebienButtonGroup.add(maisonRadioButton);
        maisonRadioButton.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        maisonRadioButton.setText("Maison");
        maisonRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        typePanel.add(maisonRadioButton);

        attributesNamePanel.add(typePanel);

        filler1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler1);

        nombienPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nombienPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombienLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombienLabel.setText("Nom du bien : ");
        nombienLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nombienPanel.add(nombienLabel);

        nombienTextField.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        nombienTextField.setPreferredSize(new java.awt.Dimension(350, 20));
        nombienTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nombienPanel.add(nombienTextField);

        attributesNamePanel.add(nombienPanel);

        filler6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler6);

        localisationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        localisationLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        localisationLabel.setText("Localisation : ");
        localisationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(localisationLabel);

        latFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        latFormattedTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        latFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        latFormattedTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(latFormattedTextField);

        latLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        latLabel.setText("lat");
        latLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(latLabel);

        filler7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(filler7);

        longFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        longFormattedTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        longFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        longFormattedTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(longFormattedTextField);

        longLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        longLabel.setText("long");
        longLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        localisationPanel.add(longLabel);

        attributesNamePanel.add(localisationPanel);

        filler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler2);

        superficiePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        superficiePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        superficieLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        superficieLabel.setText("Superficie : ");
        superficieLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        superficiePanel.add(superficieLabel);

        superficieFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        superficieFormattedTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        superficieFormattedTextField.setMinimumSize(new java.awt.Dimension(350, 20));
        superficieFormattedTextField.setPreferredSize(new java.awt.Dimension(350, 20));
        superficieFormattedTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        superficiePanel.add(superficieFormattedTextField);

        metrecarreLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        metrecarreLabel.setText("m²");
        metrecarreLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        superficiePanel.add(metrecarreLabel);

        attributesNamePanel.add(superficiePanel);

        filler3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler3);

        nbpiecesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nbpiecesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nbpiecesLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nbpiecesLabel.setText("Nombre de pièces : ");
        nbpiecesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nbpiecesPanel.add(nbpiecesLabel);

        nbpiecesSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        nbpiecesPanel.add(nbpiecesSpinner);

        attributesNamePanel.add(nbpiecesPanel);

        filler4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler4);

        commoditesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        commoditesLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        commoditesLabel.setText("Commodités : ");
        commoditesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(commoditesLabel);

        parkingCheckBox.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        parkingCheckBox.setText("Parking");
        parkingCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(parkingCheckBox);

        piscineCheckBox.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        piscineCheckBox.setText("Piscine");
        piscineCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(piscineCheckBox);

        terrasseCheckBox.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        terrasseCheckBox.setText("Terrasse");
        terrasseCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(terrasseCheckBox);

        jardinCheckBox.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jardinCheckBox.setText("Jardin");
        jardinCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(jardinCheckBox);

        caveCheckBox.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        caveCheckBox.setText("Cave");
        caveCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        commoditesPanel.add(caveCheckBox);

        attributesNamePanel.add(commoditesPanel);

        filler5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        attributesNamePanel.add(filler5);

        prixPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        prixPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        prixLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        prixLabel.setText("Prix : ");
        prixLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        prixPanel.add(prixLabel);

        prixSlider.setMaximum(1000000);
        prixSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                prixSliderStateChanged(evt);
            }
        });
        prixSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        prixPanel.add(prixSlider);

        prixValueLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        prixValueLabel.setText("0");
        prixValueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        prixPanel.add(prixValueLabel);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("€");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        prixPanel.add(jLabel2);

        attributesNamePanel.add(prixPanel);

        attributesPanel.add(attributesNamePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(attributesPanel, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des Biens", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(470, 151));
        jPanel3.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setMinimumSize(new java.awt.Dimension(200, 33));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(200, 33));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonsPanel.add(filler15);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler10);

        ajouterButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ajouterButton.setText("Ajouter");
        ajouterButton.setMaximumSize(new java.awt.Dimension(89, 23));
        ajouterButton.setMinimumSize(new java.awt.Dimension(89, 23));
        ajouterButton.setPreferredSize(new java.awt.Dimension(89, 23));
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ajouterButton);
        jPanel2.add(filler8);

        retablirButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        retablirButton.setText("Rétablir");
        retablirButton.setMaximumSize(new java.awt.Dimension(89, 23));
        retablirButton.setMinimumSize(new java.awt.Dimension(89, 23));
        retablirButton.setPreferredSize(new java.awt.Dimension(89, 23));
        retablirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retablirButtonActionPerformed(evt);
            }
        });
        jPanel2.add(retablirButton);
        jPanel2.add(filler12);

        buttonsPanel.add(jPanel2);
        buttonsPanel.add(filler14);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler11);

        supprimerButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        supprimerButton.setText("Supprimer");
        supprimerButton.setMaximumSize(new java.awt.Dimension(89, 23));
        supprimerButton.setMinimumSize(new java.awt.Dimension(89, 23));
        supprimerButton.setPreferredSize(new java.awt.Dimension(89, 23));
        supprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(supprimerButton);
        jPanel1.add(filler9);

        remplacerButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        remplacerButton.setText("Remplacer");
        remplacerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remplacerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(remplacerButton);
        jPanel1.add(filler13);

        buttonsPanel.add(jPanel1);

        jPanel3.add(buttonsPanel, java.awt.BorderLayout.LINE_START);

        bddjScrollPane.setViewportView(bddList);

        jPanel3.add(bddjScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(filler16, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Change value of house price text
     *
     * @param evt
     */
    private void prixSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_prixSliderStateChanged
        //To complete
    }//GEN-LAST:event_prixSliderStateChanged

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        //To complete
    }//GEN-LAST:event_editMouseClicked

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        //To complete
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void retablirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retablirButtonActionPerformed
        //To complete
    }//GEN-LAST:event_retablirButtonActionPerformed

    private void supprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButtonActionPerformed
        //To complete
    }//GEN-LAST:event_supprimerButtonActionPerformed

    private void remplacerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remplacerButtonActionPerformed
        //To complete
    }//GEN-LAST:event_remplacerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JRadioButton appartementRadioButton;
    private javax.swing.JPanel attributesNamePanel;
    private javax.swing.JPanel attributesPanel;
    private javax.swing.JList<String> bddList;
    private javax.swing.JScrollPane bddjScrollPane;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JCheckBox caveCheckBox;
    private javax.swing.JLabel commoditesLabel;
    private javax.swing.JPanel commoditesPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jardinCheckBox;
    private javax.swing.JFormattedTextField latFormattedTextField;
    private javax.swing.JLabel latLabel;
    private javax.swing.JLabel localisationLabel;
    private javax.swing.JPanel localisationPanel;
    private javax.swing.JFormattedTextField longFormattedTextField;
    private javax.swing.JLabel longLabel;
    private javax.swing.JRadioButton maisonRadioButton;
    private javax.swing.JLabel metrecarreLabel;
    private javax.swing.JLabel nbpiecesLabel;
    private javax.swing.JPanel nbpiecesPanel;
    private javax.swing.JSpinner nbpiecesSpinner;
    private javax.swing.JLabel nombienLabel;
    private javax.swing.JPanel nombienPanel;
    private javax.swing.JTextField nombienTextField;
    private javax.swing.JCheckBox parkingCheckBox;
    private javax.swing.JCheckBox piscineCheckBox;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JPanel prixPanel;
    private javax.swing.JSlider prixSlider;
    private javax.swing.JLabel prixValueLabel;
    private javax.swing.JButton remplacerButton;
    private javax.swing.JButton retablirButton;
    private javax.swing.JFormattedTextField superficieFormattedTextField;
    private javax.swing.JLabel superficieLabel;
    private javax.swing.JPanel superficiePanel;
    private javax.swing.JButton supprimerButton;
    private javax.swing.JCheckBox terrasseCheckBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel typePanel;
    private javax.swing.ButtonGroup typebienButtonGroup;
    // End of variables declaration//GEN-END:variables
}
